name: CI to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Build
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

#    - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#    - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1

#    - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        env:
#           RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#        with:
#          context: ./
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:$RELEASE_VERSION

#    - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
